version: '3.3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_da
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpassword
      - MYSQL_ROOT_PASSWORD=OoRoh4Sh
    ports:
      - 0.0.0.0:3309:3306
    volumes:
      - /opt/docker/mysql:/var/lib/mysql
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped

